export const ROOT = '/'
export const HOME = '/home'
// export const POSTS = '/posts'
export const USERS = '/users'
export const LOGIN = '/login'
export const LOGOUT = '/logout'
export const LOCATIONS = '/locations'